package mx.blick.migracion

class Constants {
    final static Map USER_TYPE = [admin: 1, user: 2, studio: 3, freelance: 4, quotient: 5];
    final static Map STUDIO_STATUS = [
            'pending'  : 1,
            'publicate': 2,
            'block'    : 3
    ]

    final static List USER_PROPERTIES = [
            "name",
            "lastname",
            "email",
            "password",
            "telephone",
            "userType",
            "createdAt",
            "updatedAt"
    ]
    final static List STUDIO_PROPERTIES = [
            "name",
            "certCofepris",
            "addressId",
            "publication",
            "titleImgUrl",
            "logoUrl",
            "profileImgUrl",
            "about",
            "userId",
            "status",
            "membership",
            "membershipExp",
            "id",
            "createdAt",
            "updatedAt"
    ]


    final static List FREELANCE_PROPERTIES = [
            "user",
            "membershipExp",
            "about",
            "published",
            "profileImgUrl",
            "canGoHome",
            "membership",
            "name",
            "rank",
            "createdAt",
            "updatedAt",
    ]

    final static List UNIQUE_STYLES = [
            'Abstracto',
            'Acuarela',
            'Animal',
            'Asiático',
            'Biomecánica',
            'Black Work',
            'Caligrafia',
            'Cartoon',
            'Celta',
            'Dot Work',
            'Fantasía',
            'Figurativo',
            'Geométrico',
            'Gótico',
            'Horror',
            'Ilustracion',
            'Insecto',
            'Japonés',
            'Latino',
            'Lorem Ipsum',
            'New School',
            'Old School',
            'Ornamental',
            'Polinesio',
            'Puntillismo',
            'Realismo',
            'Religioso',
            'Skull',
            'Surreal',
            'Trash Polka',
            'Tribal'
    ]

    final static Map MEXICO_STATES = [
            'Aguascalientes'                 : 1,
            'Baja California'                : 2,
            'Baja California Sur'            : 3,
            'Campeche'                       : 4,
            'Coahuila de Zaragoza'           : 5,
            'Coahuila'                       : 5,
            'Colima'                         : 6,
            'Chiapas'                        : 7,
            'Chihuahua'                      : 8,
            'Ciudad de México'               : 9,
            'Ciudad de Mexico'               : 9,
            'Distrito Federal'               : 9,
            'Durango'                        : 10,
            'Guanajuato'                     : 11,
            'Guerrero'                       : 12,
            'Hidalgo'                        : 13,
            'Jalisco'                        : 14,
            'México'                         : 15,
            'Mexico'                         : 15,
            'Estado de México'               : 15,
            'Estado de Mexico'               : 15,
            'Michoacán de Ocampo'            : 16,
            'Michoacan de Ocampo'            : 16,
            'Michoacán'                      : 16,
            'Michoacan'                      : 16,
            'Morelos'                        : 17,
            'Nayarit'                        : 18,
            'Nuevo León'                     : 19,
            'Nuevo Leon'                     : 19,
            'Oaxaca'                         : 20,
            'Puebla'                         : 21,
            'Querétaro'                      : 22,
            'Queretaro'                      : 22,
            'Quintana Roo'                   : 23,
            'San Luis Potosí'                : 24,
            'San Luis Potosi'                : 24,
            'Sinaloa'                        : 25,
            'Sonora'                         : 26,
            'Tabasco'                        : 27,
            'Tamaulipas'                     : 28,
            'Tlaxcala'                       : 29,
            'Veracruz de Ignacio de la Llave': 30,
            'Veracruz'                       : 30,
            'Yucatán'                        : 31,
            'Yucatan'                        : 31,
            'Zacatecas'                      : 32
    ]

    final static Map NORMALIZED_SUBURB_MAP = [
            'Benito Juarez'               : 'Benito Juárez',
            'Chalco'                      : 'Chalco',
            'Corregidora'                 : 'Corregidora',
            'Coyoacan'                    : 'Coyoacán',
            'Cuahutemoc'                  : 'Cuauhtémoc',
            'Cuajimalpa'                  : 'Cuajimalpa de Morelos',
            'Cuatemoc'                    : 'Cuauhtémoc',
            'Cuauhtemoc'                  : 'Cuauhtémoc',
            'Cuautemoc'                   : 'Cuauhtémoc',
            'Cuautitlan Izcalli'          : 'Cuautitlán Izcalli',
            'Cuautla'                     : 'Cuautla',
            'Gto'                         : 'Guanajuato',
            'Guadalajara'                 : 'Guadalajara',
            'Guadalupe'                   : 'Guadalupe',
            'Gustavo A Madero'            : 'Gustavo A. Madero',
            'Gustavo A. Madero'           : 'Gustavo A. Madero',
            'Hidalgo'                     : 'Hidalgo',
            'Iztapalapa'                  : 'Iztapalapa',
            'Mexicali'                    : 'Mexicali',
            'Mexicaltzingo'               : 'Mexicaltzingo',
            'Miguel Hidalgo'              : 'Miguel Hidalgo',
            'Nanchital De Lazaro Cardenas': 'Nanchital De Lazaro Cardenas',
            'Naucalpan'                   : 'Naucalpan de Juárez',
            'Puebla'                      : 'Puebla',
            'Queretaro'                   : 'Querétaro',
            'San Pedro Cholula'           : 'San Pedro Cholula',
            'Tenango Del Valle'           : 'Tenango Del Valle',
            'Texcoco De Mora'             : 'Texcoco De Mora',
            'Tlahuac'                     : 'Tlahuac',
            'Tlalnepantla'                : 'Tlalnepantla',
            'Tlalpan'                     : 'Tlalpan',
            'Toluca'                      : 'Tolúca',
            'Tuxtla Gutierrez'            : 'Tuxtla Gutiérrez',
            'Xalapa'                      : 'Xalapa',
            'Zapopan'                     : 'Zapopan',
            'Zinancatepec'                : 'Zinancatepec',
    ]
}
